apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-staging

resources:
  - ../../base

images:
  - name: 303164492950.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-devops-backend
    newTag: b3d7614435dd72092537000c6b152806cd11681f
